admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Workplace

data:
    resource: "@DataBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

